### ISSUE TITLE
newContext not have ?

### ISSUE THREAD

**Issue by Romhast** [CheshireCaat/playwright-with-fingerprints#10]
Hi, I was going to use newContext for geolocation and device, but I couldn't find such a function. Do you know?

![image](https://github.com/CheshireCaat/playwright-with-fingerprints/assets/109461554/8494b53b-ae6d-4013-be52-25983c995167)
![image](https://github.com/CheshireCaat/playwright-with-fingerprints/assets/109461554/95ce0a5a-fa49-44a3-a3c0-f6e50ca39d59)

```
const { plugin } = require('playwright-with-fingerprints');
const { readFile, writeFile } = require('fs/promises');

(async () => {
  // Get a fingerprint from the server:
  const fingerprint = await plugin.fetch('', {
    tags: ['Microsoft Windows', 'Chrome'],
  });
  await writeFile('fingerprint.json', fingerprint);
  plugin.useFingerprint(fingerprint);

  // Launch the browser instance:

  const browser = await plugin.launch({headless: false});
  const context = await browser.newContext({
    geolocation: { longitude: 41.890221, latitude: 12.492348 },
    permissions: ['geolocation']
  });

  // The rest of the code is the same as for a standard `playwright` library:
  const page = await browser.newPage();
  await page.goto('https://fingerprint.com/');
})();
```

**Comment by CheshireCaat** [comment]
As mentioned in the warning message and also in this [commit](https://github.com/CheshireCaat/playwright-with-fingerprints/commit/4dac095e9463933a6c20fb2d7563eb3912b52141) for the latest release, the **launch** method has been replaced with **launchPersistentContext**. Also please check #9 and #8.

It means that the **launch** method now returns a **BrowserContext** instance instead of a **Browser**, and also accepts options object from the **launchPersistentContext** as parameters. In order to change geolocation and so on you should use the methods described [here](https://playwright.dev/docs/api/class-browsercontext).
