### ISSUE TITLE
Why is incognito mode broken now?

### ISSUE THREAD

**Issue by dr3adx** [CheshireCaat/playwright-with-fingerprints#15]
Why remove .launch and replace it with persistent context with no option to launch in incognito mode ???

**Comment by bablosoft** [comment]
Because we need to know exact path of profile before launch in order to do some preparation.

**Comment by dr3adx** [comment]
> Because we need to know exact path of profile before launch in order to do some preparation.

what preparation, is this critical?

**Comment by CheshireCaat** [comment]
@dr3adx The developers of playwright for some reason forbade specifying the path to the profile when using the **launch** method a long time ago. However, with engine updates, a significant part of the new factors for improving anonymity has been added, which need to prepare the profile in some way before launch. 

In the case of launch, the framework itself sets a random path somewhere in the temp folders, and we cannot find it out in advance. Therefore, it was decided to limit the functionality so that later there would be no unnecessary questions and problems with anonymity. Of course, if a good workaround or direct opportunity comes along, the launch method will work just as it did before.

In order to load cookies or local storage, use a permanent profile or the **CDP** commands. If you have suggestions for the implementation of alternative methods, I will be glad to listen.

I also see that there is a feautre request in the **playwright** repository to add **storageState** to **launchPersistentContext**, so the problem may be solved by itself a little later.

**Comment by dr3adx** [comment]
> @dr3adx The developers of playwright for some reason forbade specifying the path to the profile when using the **launch** method a long time ago. However, with engine updates, a significant part of the new factors for improving anonymity has been added, which need to prepare the profile in some way before launch.
> 
> In the case of launch, the framework itself sets a random path somewhere in the temp folders, and we cannot find it out in advance. Therefore, it was decided to limit the functionality so that later there would be no unnecessary questions and problems with anonymity. Of course, if a good workaround or direct opportunity comes along, the launch method will work just as it did before.
> 
> In order to load cookies or local storage, use a permanent profile or the **CDP** commands. If you have suggestions for the implementation of alternative methods, I will be glad to listen.
> 
> I also see that there is a feautre request in the **playwright** repository to add **storageState** to **launchPersistentContext**, so the problem may be solved by itself a little later.

what anonymity problems, can you please explain this in more technical sense?

"the framework itself sets a random path somewhere in the temp folders" its always a random letter string of **constant** length, so why not just scan the folder, you already know which parent folder its gonna be

**Comment by CheshireCaat** [comment]
> you already know inside which parent folder its gonna reside.

1. OK, we will get a list of folders with profiles, we need to find out which one specifically corresponds to which browser. We still do not know in advance what kind of identifier will be generated, whether it is a constant size or not.
2. We must set up a profile **BEFORE** launching, the framework generates a path to it **DURING** launch.
3. We also cannot divide the launch into stages, because the framework does everything itself.

> what anonymity problems, can you please explain this in more technical sense?

At a minimum, the following things cannot be used/configured without a prepared profile:
1. Default browser extensions.
2. browser components.
3. Safe browsing.
4. Widevine.

And so on.
